# 应用服务 WEB 访问端口
server:
  port: 6001
  servlet:
    context-path: /demo
# 应用名称
spring:
  application:
    name: intercept-redis-url-ip
  redis:
    host: 127.0.0.1
    port: 6379
    password: huangxinwei
    timeout: 30000ms #连接超时时间 单位 ms（毫秒）
    jedis:
      pool:
        max-idle: 10 #连接池中的最大空闲连接
        min-idle: 20 #连接池中的最小空闲连接
        max-active: 10  #连接池最大活跃数。如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)
        max-wait: 3000ms  #等待可用连接的最大时间，单位毫秒，默认值为-1ms，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException


